version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres 
    restart: always
    environment:
    - POSTGRES_DB=piscineds
    - POSTGRES_USER=thbierne
    - POSTGRES_PASSWORD=mysecretpassword
    ports:
    - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - postgres_db